[package]
name = "orb-widgets"
description = "orb 组件库——组件（button/panel/menu/hud/dialog/toast 等）"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
iced.workspace = true
orb-tokens.workspace = true
orb-core.workspace = true
orb-theme.workspace = true
orb-icons.workspace = true

[lints]
workspace = true
